"""Assemble notebooks/arc2.ipynb from the modules in src/.

Kaggle wants one notebook; we want files we can diff, import and unit test. The
notebook is therefore generated, never edited by hand: every source cell is a
`%%writefile` of a file under src/, so what runs on Kaggle is byte-identical to
what the tests import.

    python build_notebook.py
"""

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")
OUT = os.path.join(HERE, "notebooks", "arc2.ipynb")
WRITEFILE_MODULES = [
    "preflight.py",
    "arc_backend.py",
    "arc_config.py",
    "arc_loader.py",
    "arc_batching.py",
    "arc_labels.py",
    "arc_confidence.py",
    "arc_decoder.py",
    "arc_solver.py",
    "starter.py",
]


def read(name):
    with io.open(os.path.join(SRC, name), encoding="utf-8") as f:
        return f.read().rstrip() + "\n"


def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


def markdown_cell(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def build():
    import sys
    sys.path.insert(0, SRC)
    import arc_config

    cells = [
        markdown_cell(
            "# ARC-AGI-2 — two-pass solver\n"
            "\n"
            "Built on the NVARC 2025 ARChitects pipeline: per-task LoRA test-time\n"
            "training on `qwen3_4b_grids15_sft139`, threshold DFS decoding, and\n"
            "augmentation re-scoring of the candidates.\n"
            "\n"
            "What is different here:\n"
            "\n"
            "- **Two passes.** Pass 1 sweeps every task on a cheap budget. The tasks\n"
            "  whose results look starved or contested are re-run in pass 2 with more\n"
            "  test-time training, more colour permutations and a looser decode\n"
            "  threshold. Both passes feed one ranking, so a revisited task\n"
            "  accumulates evidence rather than replacing it.\n"
            "- **No unsloth requirement.** It is used when present, and the run\n"
            "  falls back to plain transformers + peft when it is not, so the\n"
            "  notebook starts on any Kaggle image with only the competition and\n"
            "  the model attached.\n"
            "- **Shape prior.** When every demonstration pair agrees on how the output\n"
            "  shape follows from the input shape, candidates matching that shape are\n"
            "  promoted ahead of the ones that do not. It reorders, never drops.\n"
            "\n"
            "Set `BASELINE = True` in the config cell to fall back to the single-pass\n"
            "public baseline.\n"
            "\n"
            "Generated by `build_notebook.py` — edit `src/`, not this file.\n"
        ),
        code_cell(
            "import time\n"
            "\n"
            f"global_end_time = time.time() + 12 * 3600 - {arc_config.GLOBAL_RESERVE_SECONDS}\n"
        ),
        code_cell("!pip uninstall -y tensorflow\n"),
    ]

    for name in WRITEFILE_MODULES:
        cells.append(code_cell(f"%%writefile {name}\n" + read(name)))

    cells.append(code_cell(
        "import preflight\n"
        "import arc_config\n"
        "\n"
        "preflight.check([\n"
        "    \"/kaggle/input/competitions/arc-prize-2026-arc-agi-2\",\n"
        "])\n"
    ))

    cells.append(code_cell(
        "import os\n"
        "import subprocess\n"
        "import sys\n"
        "\n"
        "env = dict(\n"
        "    os.environ,\n"
        "    UNSLOTH_DISABLE_STATISTICS=\"1\",\n"
        "    TRITON_PTXAS_PATH=\"/usr/local/cuda/bin/ptxas\",\n"
        "    OMP_NUM_THREADS=\"12\",\n"
        "    PYTORCH_ALLOC_CONF=\"expandable_segments:True\",\n"
        "    PYTHONUNBUFFERED=\"1\",\n"
        ")\n"
        "\n"
        "proc = subprocess.Popen(\n"
        "    [sys.executable, \"starter.py\", \"--end-time\", str(global_end_time)],\n"
        "    env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,\n"
        "    text=True, bufsize=1,\n"
        ")\n"
        "for line in proc.stdout:\n"
        "    print(line, end=\"\")\n"
        "starter_exit = proc.wait()\n"
        "print(f\"*** starter.py exit code: {starter_exit}\")\n"
        "if starter_exit != 0:\n"
        "    raise RuntimeError(\n"
        "        f\"starter.py failed (exit {starter_exit}). Stopping here rather \"\n"
        "        f\"than writing a submission full of placeholders.\"\n"
        "    )\n"
    ))
    cells.append(code_cell(read("submit_cell.py")))

    nb = {
        "cells": cells,
        "metadata": {
            "kaggle": {
                "accelerator": "nvidiaL4",
                "dataSources": [
                    {"sourceType": "competition", "sourceId": 133469},
                    {"sourceType": "modelInstanceVersion", "sourceId": 627758},
                ],
                "isInternetEnabled": False,
                "language": "python",
                "sourceType": "notebook",
                "isGpuEnabled": True,
            },
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11.13"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
        f.write("\n")

    print(f"wrote {OUT} ({len(cells)} cells)")


if __name__ == "__main__":
    build()
